/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidacaoRouteImport } from './routes/validacao'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RoteirizarRouteImport } from './routes/roteirizar'
import { Route as RetirasRouteImport } from './routes/retiras'
import { Route as BloqueadosRouteImport } from './routes/bloqueados'
import { Route as IndexRouteImport } from './routes/index'

const ValidacaoRoute = ValidacaoRouteImport.update({
  id: '/validacao',
  path: '/validacao',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirizarRoute = RoteirizarRouteImport.update({
  id: '/roteirizar',
  path: '/roteirizar',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirasRoute = RetirasRouteImport.update({
  id: '/retiras',
  path: '/retiras',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueadosRoute = BloqueadosRouteImport.update({
  id: '/bloqueados',
  path: '/bloqueados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bloqueados': typeof BloqueadosRoute
  '/retiras': typeof RetirasRoute
  '/roteirizar': typeof RoteirizarRoute
  '/setup': typeof SetupRoute
  '/upload': typeof UploadRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bloqueados': typeof BloqueadosRoute
  '/retiras': typeof RetirasRoute
  '/roteirizar': typeof RoteirizarRoute
  '/setup': typeof SetupRoute
  '/upload': typeof UploadRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bloqueados': typeof BloqueadosRoute
  '/retiras': typeof RetirasRoute
  '/roteirizar': typeof RoteirizarRoute
  '/setup': typeof SetupRoute
  '/upload': typeof UploadRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bloqueados'
    | '/retiras'
    | '/roteirizar'
    | '/setup'
    | '/upload'
    | '/validacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bloqueados'
    | '/retiras'
    | '/roteirizar'
    | '/setup'
    | '/upload'
    | '/validacao'
  id:
    | '__root__'
    | '/'
    | '/bloqueados'
    | '/retiras'
    | '/roteirizar'
    | '/setup'
    | '/upload'
    | '/validacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BloqueadosRoute: typeof BloqueadosRoute
  RetirasRoute: typeof RetirasRoute
  RoteirizarRoute: typeof RoteirizarRoute
  SetupRoute: typeof SetupRoute
  UploadRoute: typeof UploadRoute
  ValidacaoRoute: typeof ValidacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validacao': {
      id: '/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof ValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteirizar': {
      id: '/roteirizar'
      path: '/roteirizar'
      fullPath: '/roteirizar'
      preLoaderRoute: typeof RoteirizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retiras': {
      id: '/retiras'
      path: '/retiras'
      fullPath: '/retiras'
      preLoaderRoute: typeof RetirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueados': {
      id: '/bloqueados'
      path: '/bloqueados'
      fullPath: '/bloqueados'
      preLoaderRoute: typeof BloqueadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BloqueadosRoute: BloqueadosRoute,
  RetirasRoute: RetirasRoute,
  RoteirizarRoute: RoteirizarRoute,
  SetupRoute: SetupRoute,
  UploadRoute: UploadRoute,
  ValidacaoRoute: ValidacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
